### ISSUE TITLE
Incorrect export/import

### ISSUE THREAD

**Issue by nitramiz** [flexemarkets/fm-issues#1]
After making a trade between test1 and test2, the export file didn't contain the changes in the accounts. Stocks and cash remained unchanged. 
Test1 and test2's views had changed stock and cash amounts, but the csv had default values (20 stocks, 330 cash).
Balances didn't change after importing the exported file with the default (wrong) values - the balances for test1 and test2 were what they were supposed to be after the completion of the transaction of buying/selling a stock between them, so the export/import didn't affect the interface/database.

**Comment by nitramiz** [comment]
Checked to see if bug persists, it does. Tried exporting a file while market is still open, while paused and after being stopped, same thing - no change in balances in csv.
It is under marketplaces #29 (from URL - marketplaces/29).
Tried in marketplace 28 - incorrect csv and test1 and test2 balances after a couple of trades from UI.

**Comment by JanStureNielsen** [comment]
I'm not able to reproduce this, @nitram-iz -- can you provide additional details? Here's my test. In a new marketplace "dev@dev" placed a single SELL order for 1 unit at $5.00. The export correctly showed:

![image](https://cloud.githubusercontent.com/assets/4248566/26832152/cc2cc834-4a8b-11e7-8796-db603f228ae3.png)

with no changes in settled cash and assets (since there is no trade):

![image](https://cloud.githubusercontent.com/assets/4248566/26832191/ecc54bfc-4a8b-11e7-8f80-e93307f1a864.png)

Then "test0@test.com" placed a single BUY order for 1 unit at $5.00 which resulted in a trade and the export correctly shows:

![image](https://cloud.githubusercontent.com/assets/4248566/26832258/1eaa3b1e-4a8c-11e7-8b59-cf10f9cc4fc7.png)

with the expected changes to the settled cash and assets:

![image](https://cloud.githubusercontent.com/assets/4248566/26832303/46818372-4a8c-11e7-9e53-2d42bf8c1d33.png)

**Comment by JanStureNielsen** [comment]
Please re-open with steps to reproduce the export problem, @nitram-iz.

I have focused this issue on the first issue you reported above: "export file didn't contain the changes in the accounts". You included a second issue which I have ignored -- for traceability, please report only a single issue per GitHub issue. If you can reproduce the import issue, please open a new issue on that with the steps to reproduce.

**Comment by JanStureNielsen** [comment]
I have focused this issue on the first issue you reported: "export file didn't contain the changes in the accounts". You included a second issue which I have ignored -- for traceability, please report only a single issue per GitHub issue. If you can reproduce the import issue, please open a new issue on that with the steps to reproduce.
