### ISSUE TITLE
Inconsistent Content-Type header in API Responses

### ISSUE THREAD

**Issue by darkfishy** [flexemarkets/fm-issues#21]
The `Content-Type` for certain API endpoints are not consistent, where they should be either of `Content-Type: application/json; charset=utf-8` or `Content-Type: application/hal+json;charset=UTF-8`; latter being the one in use for most responses.

Endpoints such as ones below, return `Content-Type: text/html;charset=UTF-8`:
1. https://fm-data.herokuapp.com/api/profile/markets
2. https://fm-data.herokuapp.com/api/profile/allocations
3. Other endpoints under `/profile` tree

There are sometimes error responses as well with the incorrect `Content-Type` of `text/html`. Will note them later when recognised.

**Comment by JanStureNielsen** [comment]
The endpoints under `/api/profile` should all be:

    Content-Type: application/alps+json;charset=UTF-8

which they (at least now) appear to be.

**Comment by darkfishy** [comment]
Doesn't seem to have been fixed or in effect yet. Check [this](https://youtu.be/27LTK7foAFQ).

**Comment by JanStureNielsen** [comment]
Would you provide the curl(s) for the inconsistency(ies)?

**Comment by JanStureNielsen** [comment]
It looks like this is a client accept header issue. Via curl:

    curl -u $FM_DEV https://fm-data.herokuapp.com/api/profile/markets

sends

    Accept: */*

and receives

    Content-Type: application/alps+json;charset=UTF-8

as expected. But the browser is sending:

    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8

and receiving:

    Content-Type: text/html;charset=UTF-8

even though the content actually is `application/alps+json`. This is unfortunate, but I don't expect this to have a big impact because anything reading the ALPS profile is going to process it as `application/alps+json` regardless of the content type. If you feel strongly otherwise, let me know.
