### ISSUE TITLE
FM Server throws application error via API

### ISSUE THREAD

**Issue by nitinef** [flexemarkets/fm-issues#8]
Case: A simple robot sends an order every second and cancels them after two seconds. After a few minutes, the server sends the following error response.
```
{'code': 503, 'response': '<!DOCTYPE html>\n\t<html>\n\t  <head>\n\t\t<meta name="viewport" content="width=device-width, initial-scale=1">\n\t\t<meta charset="utf-8">\n\t\t<title>Application Error</title>\n\t\t<style media="screen">\n\t\t  html,body,iframe {\n\t\t\tmargin: 0;\n\t\t\tpadding: 0;\n\t\t  }\n\t\t  html,body {\n\t\t\theight: 100%;\n\t\t\toverflow: hidden;\n\t\t  }\n\t\t  iframe {\n\t\t\twidth: 100%;\n\t\t\theight: 100%;\n\t\t\tborder: 0;\n\t\t  }\n\t\t</style>\n\t  </head>\n\t  <body>\n\t\t<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>\n\t  </body>\n\t</html>'}
```

**Comment by JanStureNielsen** [comment]
Look like connection leak:

```
Caused by: org.apache.tomcat.jdbc.pool.PoolExhaustedException: [http-nio-38743-exec-137] Timeout: Pool empty. Unable to fetch a connection in 30 seconds, none available[size:115; busy:115; idle:0; lastwait:30000].
```

**Comment by JanStureNielsen** [comment]
@nitinef -- are you only running a single robot when this happens? At one order per second, a "few minutes" is likely less than 1000 LIMIT orders + 1000 CANCEL orders, right?

**Comment by JanStureNielsen** [comment]
The root cause of this is null pointer exception caused by not validating the existence of the target of a CANCEL order. 

When submitting a LIMIT order, an order is verified, saved, and processed. In between the save and processed stage, clients are notified of the order's existence which allows a client to submit a CANCEL order. This is a performance optimization which results in a race-condition: if a LIMIT order's processing takes longer than it take a client to submit a CANCEL for that LIMIT order, then the LIMIT will not be found when the CANCEL order is submitted (because the LIMIT order is still being processed). In this case, the client is notified that the order "doesn't exist" (which is technically true but could be improved/clarified) but since the client knows that it does exist (i.e., it will exist at some point in the near future) the client should re-try the CANCEL.

To simplify things in the short-term, I will remove this notification optimization which will eliminate the race-condition. If/when we want this optimization we can update clients to re-try on CANCEL failures with known-to-exist LIMIT orders.

**Comment by nitinef** [comment]
Yes. I am running a single robot with regular polling of order book and
marketplace status.
